### ISSUE TITLE
Colab FileNotFoundError

### ISSUE THREAD

**Issue by PavelGrigorev** [yael-vinker/CLIPasso#1]
Hey, Yael-Vinker!
I faced NotFound error running Colab :
FileNotFoundError: [Errno 2] No such file or directory: '/content/CLIPasso/output_sketches/camel//camel_32strokes_seed0/config.npy'
and wonder what is supposed to be there?

**Comment by yael-vinker** [comment]
Hello Pavel, thanks for your interest in our work!
This file should appear after the successful creation of a single sketch (with seed0), receiving this exception means that something went wrong when running the code previously.

Can you please provide more details about the error?
1. In which of the stages did it happen? (stage 2 or 3) 
2. Can you please share the full exception traceback? (i.e. the entire output you received before this line)

**Comment by Quasimondo** [comment]
I am getting the same error when trying to follow the quick start example that uses run_object_sketching.py - it seems to be connected with the f"{something}" string formatting in some of the logging/saving utils (maybe it is a python version issue?)

**Comment by Quasimondo** [comment]
If it is of any help for someone else I found the cause of the error in my case - there is a hardcoded "python" command inside the run_object_sketching.py code which in my case launches a python 2 instance since my machine uses "python3" to run python3 - this also caused the string related errors. 

So renaming 
`exit_codes.append(sp.run(["python", "painterly_rendering.py", target,`
to
`exit_codes.append(sp.run(["python3", "painterly_rendering.py", target,`

in run_object_sketching.py fixed it for me

**Comment by jthteo** [comment]
Encountered same issue. Docker installation as per instructions but when >python run_object,,,,, the following happens:


Processing [camel.png] ...
Results will be saved to
[/home/vinker/CLIPSketch/output_sketches/camel/] ...
==================================================
GPU: True
100%|████████████████████████████████████████| 278M/278M [04:57<00:00, 982kiB/s]
Traceback (most recent call last):
  File "run_object_sketching.py", line 99, in <module>
    run(seed, wandb_name)
  File "run_object_sketching.py", line 83, in run
    allow_pickle=True)[()]
  File "/home/vinker/miniconda/envs/habitat/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/vinker/CLIPSketch/output_sketches/camel//camel_16strokes_seed0/config.npy'

**Comment by 04RR** [comment]
Hey I encountered same issue.

**Comment by PavelGrigorev** [comment]
It happen in Second Stage.
And the full traceback is:
Results will be saved to 
[/content/CLIPasso/output_sketches/camel/] ...
==================================================
GPU: True
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/content/CLIPasso/run_object_sketching.py](https://localhost:8080/#) in <module>()
     97         P.apply_async(run, (seed, wandb_name))
     98     else:
---> 99         run(seed, wandb_name)
    100 
    101 if multiprocess:

1 frames
[/content/CLIPasso/run_object_sketching.py](https://localhost:8080/#) in run(seed, wandb_name)
     81                               "--display_logs", str(int(args.colab))]))
     82     config = np.load(f"{output_dir}/{wandb_name}/config.npy",
---> 83                      allow_pickle=True)[()]
     84     loss_eval = np.array(config['loss_eval'])
     85     inds = np.argsort(loss_eval)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    414             fid = file
    415             own_fid = False
--> 416         else:
    417             fid = stack.enter_context(open(os_fspath(file), "rb"))
    418             own_fid = True

FileNotFoundError: [Errno 2] No such file or directory: '/content/CLIPasso/output_sketches/camel//camel_32strokes_seed0/config.npy'

Thank you for response!

**Comment by yael-vinker** [comment]
@PavelGrigorev did you restart the runtime after stage 1? with "Runtime > Restart runtime"
If not, please try to restart the runtime and then rerun stage 2 - please let me know if it worked.
If you did, can you please tell me if you see any files under "output_sketches/camel"?

**Comment by PavelGrigorev** [comment]
I got it!!!
I did not restart the kernel in stage 1
Now it works fine!
thank you for sharing your awesome work!

**Comment by yael-vinker** [comment]
@PavelGrigorev great! thanks for your update :)

**Comment by yael-vinker** [comment]
Hi @jthteo, note that I opened a new issue for your response as you used Docker and not colab, so you experienced a different issue :) please reply on the new thread.

Same for @04RR - please provide more details on your environment (docker? colab? pip?) in a new related issue, in case you used colab, and you had the same problem as Pavel's, ignore this comment :)
