### ISSUE TITLE
SystemExit: 1 Error

### ISSUE THREAD

**Issue by raynt** [yael-vinker/CLIPasso#10]
When testing out the default settings in the Colab notebook I am getting the following error in the 'Start Sketching' stage:

Results will be saved to 
[/content/CLIPasso/output_sketches/rose/] ...
==================================================
GPU: True
An exception has occurred, use %tb to see the full traceback.
SystemExit: 1

I've run the notebook in the past successfully so this seems to be a new development.

![Screen Shot 2022-05-07 at 2 31 41 PM](https://user-images.githubusercontent.com/17106015/167267259-dca5b757-82c5-4d51-89f2-3804266b120f.png)

**Comment by yael-vinker** [comment]
I uploaded a new version with a potential fix, please pull the new code and let me know if you still face this error (:
