### ISSUE TITLE
ModuleAttributeError: 'ModifiedResNet' object has no attribute 'relu'

### ISSUE THREAD

**Issue by LittleFlyFish** [yael-vinker/CLIPasso#11]
I found the output results on docker and on local computer is very different with the same environment and code. 

When I run it in docker, it can run successfully without any bugs. But when I run the exactly same code without change on my own computer. it run out an error:

torch.nn.modules.module.ModuleAttributeError: 'ModifiedResNet' object has no attribute 'relu'

It is about the line 455 in loss.py:

![image](https://user-images.githubusercontent.com/26098258/167636294-18dc7ef0-2020-409c-a8b3-607421b07085.png)

If I change the line m.relu into m.relu1 or nn.relu(). The bug will be fixed. However, the result will be very wired. It seems the network didn't keep updating.

![best_iter](https://user-images.githubusercontent.com/26098258/167636684-4faeeb56-2d10-44f2-84a2-e4727b6d0e6f.jpg)

I don't know why it happens and how to solve this kind of problem. The version of python packages like torch and PyTorch are exactly the same. The only difference may be the Cuda is 11.6 on the local computer and the Cuda is 10.3 on docker. Is that will affect the result?

Could you give me some advice?

Many Thanks!

**Comment by LittleFlyFish** [comment]
This issue is solved：

The problem seems like the local computer didn't load in the right 'RN101' model because of packages version problems. So I will load and save RN101 model in docker and download the model from docker to local computer.

I change:

        self.model, clip_preprocess = clip.load(
            self.clip_model_name, args.device, jit=False)
        # torch.save(self.model, 'RN101.pt')
        self.model = torch.load('/home/soe/Documents/MyProjects/CLIPasso/models/RN101.pt')

in loss.py line 356-359

And I change relu1 relu2 relu3 in model.py in clip python package into relu. 

The the whole problem solved and the code works the same like in docker.

**Comment by yael-vinker** [comment]
Hi, thanks a lot for sharing your solution!
This error happens because CLIP source code has been modified in the latest push:
https://github.com/openai/CLIP/commit/b46f5ac7587d2e1862f8b7b1573179d80dcdd620
One option could also be to replace the "import clip" in models/loss.py with "import CLIP_.clip as clip", and you should also comment line 31 "clip_text": CLIPTextLoss(args)" in loss.py

For now, I am closing this issue. Let me know if you need any further help :)

**Comment by LittleFlyFish** [comment]
Hi Yael-Vinker,

That's very helpful! Thank you very much!

Best Regards,

LittleFlyFish

**Comment by LittleFlyFish** [comment]
Hi Yael-Vinker,

I am trying to do more experiments with the python package diffvg. However,
I didn't find many explanations of their functions and usage on GIthub
https://github.com/BachiLi/diffvg/issues

Could you give me some guidances to learn how to use the functions and
packages of DIFFVG? That would be very helpful for my current project!

Many appreciations!

Best Regards,

LittleFlyFish
