### ISSUE TITLE
No such file or directory: '..../camel_16strokes_seed0/config.npy' (Docker installation)

### ISSUE THREAD

**Issue by yael-vinker** [yael-vinker/CLIPasso#2]
Encountered same issue. Docker installation as per instructions but when >python run_object,,,,, the following happens:

Processing [camel.png] ...
Results will be saved to
[/home/vinker/CLIPSketch/output_sketches/camel/] ...
==================================================
GPU: True
100%|████████████████████████████████████████| 278M/278M [04:57<00:00, 982kiB/s]
Traceback (most recent call last):
  File "run_object_sketching.py", line 99, in <module>
    run(seed, wandb_name)
  File "run_object_sketching.py", line 83, in run
    allow_pickle=True)[()]
  File "/home/vinker/miniconda/envs/habitat/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/vinker/CLIPSketch/output_sketches/camel//camel_16strokes_seed0/config.npy'

_Originally posted by @jthteo in https://github.com/yael-vinker/CLIPasso/issues/1#issuecomment-1039114457_

**Comment by yael-vinker** [comment]
Hi, can you please check if you have any files under "CLIPSketch/output_sketches/camel/camel_16strokes_seed0"?
Also, can you please check if u2net trained weights were downloaded successfully, it should be under "/CLIPSketch/U2Net_/saved_models/u2net.pth".

**Comment by jthteo** [comment]
Thanks for moving here

u2net.pth is in the correct directory.
../camel_16strokes_seed0 contains two empty directories: jpg_logs and svg_logs

**Comment by leonardopetrini** [comment]
Possibly an extra `/` is present in `run_object_sketching.py` either at line [45](https://github.com/yael-vinker/CLIPasso/blob/7478f4886d5ed670b8231ff58e6521d9f5235b66/run_object_sketching.py#L45) or [82](https://github.com/yael-vinker/CLIPasso/blob/7478f4886d5ed670b8231ff58e6521d9f5235b66/run_object_sketching.py#L82)..?

**Comment by jthteo** [comment]
Line 42 does not seem to the problem.

Line 82 seems to be referring to a non-existent config.npy file which is named in the error message. I cannot find any sign of this file in the folders. I tried renaming and putting the config.py file from the main directory but it doesn't work either as it doesn't recognise it as for the pickel.

**Comment by yael-vinker** [comment]
This error means that there was an exception during running. When execution is done successfully, a "config.npy" file should appear with all the information about the specific session.
I pushed an update to print a more informative error message.
Can you please follow the instructions **from scratch** with the updated version and let me know what error message do you get?(:
