### ISSUE TITLE
Editing the Brush Style on SVGs

### ISSUE THREAD

**Issue by ximinng** [yael-vinker/CLIPasso#25]
Congratulations, **CLIPasso is a very rewarding job**. I have a few questions to ask: How to change the definition of primitives or the effects of brushes displayed on your project home page. Thank you

**Comment by Yi-Lynn** [comment]
I have the same questions :) Do you have any thoughts about how to edit the brush style on top of vectorized strokes?

Btw, I've read your paper DiffSketcher -- really solid and inspiring work.

**Comment by yael-vinker** [comment]
Hi, thanks you for your interest in our work and sorry for the delay.
I used Adobe Illustrator. you can load the SVG into the program and then edit the sketch very easily with "Stroke Panel" or "Stroke Options." This panel allows you to adjust various properties of the stroke, such as its weight, color, dash pattern, and brush style.
