### ISSUE TITLE
u2net.pth unable to automatically download due to permission issue

### ISSUE THREAD

**Issue by teyou** [yael-vinker/CLIPasso#4]
When I run this command from the provided docker image
`python run_object_sketching.py --target_file "camel.png"`

It shows this error:
```
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ 
```

**Comment by teyou** [comment]
the fix is simply to change the gdown version to the latest one

ref: https://github.com/wkentaro/gdown/issues/43

If still have issue, can try this step
```
pip install --upgrade --no-cache-dir gdown

then 
1. cd to `./U2Net_/saved_models/`
2. run gdown https://drive.google.com/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ 
```

**Comment by yael-vinker** [comment]
Hi @teyou, thanks for your interest in our project, and thanks for sharing your solution.

Another possible solution in case the provided link is not working, is using this command to download the trained weights of u2net from huggingface:
wget https://huggingface.co/akhaliq/CLIPasso/resolve/main/u2net.pth --output-document=U2Net_/saved_models/u2net.pth

(Credit to @AK391 for uploading this file).
