### ISSUE TITLE
Some errors on Google Colab.

### ISSUE THREAD

**Issue by jam411** [yael-vinker/CLIPasso#6]
Hi, yael-vinker nice work CLIPasso! Thank you.
I tried to run it on google colab but I got some errors, so I will share some changes until it worked.

1. Down grade Tensorflow to version 1.X.
`%tensorflow_version 1.x`
`import tensorflow as tf`
`print(tf.__version__)`

2. Add "pydiffvg" path to c compiled file?
`import sys`
`sys.path.append("/content/CLIPasso/diffvg/build/lib.linux-x86_64-3.7")`

5. Upgrade Pillow.
`!pip3 install --upgrade Pillow`

**Comment by yael-vinker** [comment]
Hi @jam411, thank you very much for solving this issue and sharing your solution!
Your changes indeed solved the compilation error, the colab in now updated with your fix.
Many thanks!
