### ISSUE TITLE
Diffvg not compiled with GPU

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [yael-vinker/CLIPasso#7]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/68578066/161188331-bda4a5d6-f44c-441f-93ea-db40b8fcee65.png">

Hi, I would like to ask how to solve the problem. I followed the installation guidance in your github repo. But it occurs this error. Do you know how to fix it? Thanks!

**Comment by yael-vinker** [comment]
Hello, did you use the pip or docker version ?

**Comment by AlonzoLeeeooo** [comment]
> 

I use `python setup.py` for installation. The problem is now fixed by changing `DIFFVG_CUDA = 1`.

**Comment by yael-vinker** [comment]
great thanks for letting me know. I am closing this issue (:
